// Code generated by protoc-gen-go.
// source: helloworld.proto
// DO NOT EDIT!

/*
Package helloworld is a generated protocol buffer package.

It is generated from these files:
	helloworld.proto

It has these top-level messages:
	HelloRequest
	HelloReply
	HighRequest
	HighReply
*/
package helloworld

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

// The request message containing the user's name.
type HelloRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// The response message containing the greetings
type HelloReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *HelloReply) Reset()                    { *m = HelloReply{} }
func (m *HelloReply) String() string            { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()               {}
func (*HelloReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type HighRequest struct {
	Name    string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *HighRequest) Reset()                    { *m = HighRequest{} }
func (m *HighRequest) String() string            { return proto.CompactTextString(m) }
func (*HighRequest) ProtoMessage()               {}
func (*HighRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type HighReply struct {
	Count   int32  `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (m *HighReply) Reset()                    { *m = HighReply{} }
func (m *HighReply) String() string            { return proto.CompactTextString(m) }
func (*HighReply) ProtoMessage()               {}
func (*HighReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*HelloRequest)(nil), "helloworld.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "helloworld.HelloReply")
	proto.RegisterType((*HighRequest)(nil), "helloworld.HighRequest")
	proto.RegisterType((*HighReply)(nil), "helloworld.HighReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion2

// Client API for Greeter service

type GreeterClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	HighFive(ctx context.Context, opts ...grpc.CallOption) (Greeter_HighFiveClient, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := grpc.Invoke(ctx, "/helloworld.Greeter/SayHello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) HighFive(ctx context.Context, opts ...grpc.CallOption) (Greeter_HighFiveClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Greeter_serviceDesc.Streams[0], c.cc, "/helloworld.Greeter/HighFive", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterHighFiveClient{stream}
	return x, nil
}

type Greeter_HighFiveClient interface {
	Send(*HighRequest) error
	Recv() (*HighReply, error)
	grpc.ClientStream
}

type greeterHighFiveClient struct {
	grpc.ClientStream
}

func (x *greeterHighFiveClient) Send(m *HighRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greeterHighFiveClient) Recv() (*HighReply, error) {
	m := new(HighReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Greeter service

type GreeterServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	HighFive(Greeter_HighFiveServer) error
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_HighFive_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreeterServer).HighFive(&greeterHighFiveServer{stream})
}

type Greeter_HighFiveServer interface {
	Send(*HighReply) error
	Recv() (*HighRequest, error)
	grpc.ServerStream
}

type greeterHighFiveServer struct {
	grpc.ServerStream
}

func (x *greeterHighFiveServer) Send(m *HighReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greeterHighFiveServer) Recv() (*HighRequest, error) {
	m := new(HighRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "HighFive",
			Handler:       _Greeter_HighFive_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
}

var fileDescriptor0 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0xc8, 0x48, 0xcd, 0xc9,
	0xc9, 0x2f, 0xcf, 0x2f, 0xca, 0x49, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x42, 0x88,
	0x28, 0x29, 0x71, 0xf1, 0x78, 0x80, 0x78, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x42,
	0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x92,
	0x1a, 0x17, 0x17, 0x54, 0x4d, 0x41, 0x4e, 0xa5, 0x90, 0x04, 0x17, 0x7b, 0x6e, 0x6a, 0x71, 0x71,
	0x62, 0x3a, 0x4c, 0x11, 0x8c, 0xab, 0x64, 0xcd, 0xc5, 0xed, 0x91, 0x99, 0x9e, 0x81, 0xc7, 0x28,
	0x90, 0xe6, 0xe4, 0xfc, 0xbc, 0x92, 0xd4, 0xbc, 0x12, 0x09, 0x26, 0xa0, 0x30, 0x4f, 0x10, 0x8c,
	0x0b, 0xd4, 0xcc, 0x09, 0xd1, 0x0c, 0xb2, 0x43, 0x84, 0x8b, 0x35, 0x39, 0xbf, 0x14, 0xa8, 0x08,
	0xa4, 0x97, 0x35, 0x08, 0xc2, 0xc1, 0xad, 0xd9, 0xa8, 0x9b, 0x91, 0x8b, 0xdd, 0xbd, 0x28, 0x35,
	0xb5, 0x24, 0xb5, 0x48, 0xc8, 0x8e, 0x8b, 0x23, 0x38, 0xb1, 0x12, 0xec, 0x60, 0x21, 0x09, 0x3d,
	0x24, 0xcf, 0x23, 0xfb, 0x53, 0x4a, 0x0c, 0x8b, 0x0c, 0xd0, 0x66, 0x25, 0x06, 0x21, 0x07, 0x2e,
	0x0e, 0x90, 0x43, 0xdc, 0x32, 0xcb, 0x52, 0x85, 0xc4, 0x51, 0x54, 0x21, 0xfc, 0x26, 0x25, 0x8a,
	0x29, 0x01, 0xd6, 0xad, 0xc1, 0x68, 0xc0, 0xe8, 0x64, 0xc0, 0x25, 0x9d, 0x99, 0xaf, 0x97, 0x5e,
	0x54, 0x90, 0xac, 0x97, 0x5a, 0x91, 0x98, 0x5b, 0x90, 0x93, 0x5a, 0x8c, 0xa4, 0xdc, 0x89, 0x1f,
	0x6c, 0x5d, 0x38, 0x88, 0x1d, 0x00, 0x8a, 0x8f, 0x00, 0xc6, 0x24, 0x36, 0x70, 0xc4, 0x18, 0x03,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x3a, 0xb2, 0x0a, 0x59, 0xac, 0x01, 0x00, 0x00,
}
